### PR TITLE
[EthereumKeyStore] Use syncScrypt instead of scrypt

### LINKED ISSUE #11: Scrypt.js sync/async
Hello,

Do you really need async `scrypt` there? You don't use `progressCallback`.
https://github.com/bloxapp/ssv-keys/blob/main/src/lib/EthereumKeyStore/EthereumKeyStore.ts#L132

Unfortunately, async `scrypt`works much slower in browser. You can check it using your react example.
Is it possible to use `syncScrypt` instead?

### PR DESCRIPTION
**Pull request by arsoba**
Fixes #11 

As [EthereumKeyStore](https://github.com/bloxapp/ssv-keys/blob/v2/src/lib/EthereumKeyStore/EthereumKeyStore.ts#L136) do not use `scrypt` `progressCallback`, I propose to use `syncScrypt` instead. There is no difference on nodejs, but in browsers `scrypt` works much slower.

And there are two videos to compare how fast `syncScrypt` in browser:

1. scrypt
https://www.loom.com/share/59dff172bd1d40b0a496e2128d4c45f0

2. syncScrypt
https://www.loom.com/share/22f3ee2cfc5c4df2ba7911599ef1501a
 

- [x] Tests pass

### CODE REVIEW

**Comment by andrew-blox** [comment]
Hey @arsoba!
Thanks for the PR and taking the time to provide good comments and great examples!
We noticed that we had a few changes to align and just now aligned all to main.
Can you please push your changes again to our newly aligned main?
We can do ourselves as well if you want, but wanna give you the credit ;) !!

**Comment by arsoba** [comment]
@andrew-blox sure, I will do.

**Comment by arsoba** [comment]
@andrew-blox now it's pointed to the main branch

**Review by meshin-blox — APPROVED** [review]

**Comment by andrew-blox** [comment]
@arsoba 

We just wanted to say a huge thank you for your contribution!! Your pull request was absolutely spot-on.  I tested this and can see a huge improvement! We are truly grateful for your help and expertise.

Thank you again for your dedication. Keep rocking!

**Pull request merged**
